# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('movie_id', models.CharField(max_length=10, unique=True)),
                ('genre', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=10)),
            ],
        ),
    ]
