# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_id',
            field=models.CharField(max_length=10),
        ),
    ]
