# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20171123_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='query',
            field=models.CharField(default='', max_length=100),
        ),
    ]
