# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=1, max_length=2),
        ),
    ]
