# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieinfo_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='poster',
            field=models.CharField(default='No poster available', max_length=100),
        ),
    ]
