# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movieinfo_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=10)),
                ('query', models.CharField(max_length=10)),
                ('poster', models.CharField(default='No poster available', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='movieinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='page',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.MovieInfo'),
        ),
    ]
