# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movieinfo_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='cast',
            field=models.CharField(default='No cast', max_length=500),
        ),
    ]
